services:
  adema:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    container_name: adema
    env_file:
      - .env
    ports:
      - "8181:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - graphql_my_network
    restart: "no"

networks:
  graphql_my_network:
    external: true
